// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PluginCommonBase","status":true,"description":"パラメータ解析を提供する共通基盤です","parameters":{}},
{"name":"EffekseerForRPGMakerMZ_Ex","status":true,"description":"Effekseer 拡張プラグイン v1.62 - 1.03","parameters":{"InstanceMaxCount":"10000","SquareMaxCount":"10000","DistortionEnabled":"false"}},
{"name":"MPP_Pseudo3DBattle","status":true,"description":"戦闘中、立体的にカメラが移動する機能が追加されます。","parameters":{"Battleback Scale":"1.3","Drift Delay":"120","Battleback2 Pivot Y Fixes":"[\"{\\\"Battleback2 Image\\\":\\\"\\\",\\\"Pivot Y\\\":\\\"182\\\"}\"]"}},
{"name":"SimpleMsgSideViewMZ","status":true,"description":"[Ver1.2.0]サイドビューバトルでスキル/アイテムの名前のみ表示","parameters":{"displayAttack":"false","displayIcon":"true","doesShowDesc":"false","descTiming":"1"}}
];
